-- =============================================
-- SECTION 1: DATABASE & TABLE CREATION (DDL)
-- =============================================

-- 1. Create a new database
CREATE DATABASE db_gadget_retail;

-- 2. Select the database to use
USE db_gadget_retail;

-- 3. Create 'customers' table
CREATE TABLE customers (
    customer_id INT AUTO_INCREMENT PRIMARY KEY,
    full_name VARCHAR(100),
    city VARCHAR(50),
    email VARCHAR(100),
    registration_date DATE
);

-- 4. Create 'products' table
CREATE TABLE products (
    product_id INT AUTO_INCREMENT PRIMARY KEY,
    product_name VARCHAR(100),
    category VARCHAR(50),
    price DECIMAL(10, 2),
    stock INT
);

-- 5. Create 'transactions' table
CREATE TABLE transactions (
    transaction_id INT AUTO_INCREMENT PRIMARY KEY,
    customer_id INT,
    product_id INT,
    transaction_date DATE,
    quantity INT,
    total_amount DECIMAL(10, 2),
    
    -- Foreign Key to customers table
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id),
    
    -- Foreign Key to products table
    FOREIGN KEY (product_id) REFERENCES products(product_id)
);

-- =============================================
-- SECTION 2: INSERTING DATA (DML)
-- =============================================

-- 1. Insert data into 'customers'
INSERT INTO customers (full_name, city, email, registration_date)
VALUES
('Andi Saputra', 'Jakarta', 'andi@gmail.com', '2023-01-15'),
('Budi Santoso', 'Bandung', 'budi.san@yahoo.com', '2023-02-20'),
('Citra Lestari', 'Surabaya', 'citra.l@gmail.com', '2023-03-10'),
('Dewi Anggraini', 'Jakarta', 'dewi.a@outlook.com', '2023-04-05'),
('Eko Prasetyo', 'Yogyakarta', 'eko.p@gmail.com', '2023-05-12');

-- 2. Insert data into 'products'
INSERT INTO products (product_name, category, price, stock)
VALUES
('iPhone 14 Pro', 'Smartphone', 18000000, 10),
('Samsung Galaxy S23', 'Smartphone', 15000000, 15),
('MacBook Air M2', 'Laptop', 20000000, 5),
('Asus ROG Zephyrus', 'Laptop', 25000000, 3),
('AirPods Pro 2', 'Accessories', 3500000, 50);

-- 3. Insert data into 'transactions'
INSERT INTO transactions (customer_id, product_id, transaction_date, quantity, total_amount)
VALUES
-- Trans 1: Andi buys iPhone (1 unit)
(1, 1, '2023-06-01', 1, 18000000),

-- Trans 2: Budi buys AirPods (2 units) -> VOLUME LEADER
(2, 5, '2023-06-02', 2, 7000000),

-- Trans 3: Andi buys MacBook (1 unit)
(1, 3, '2023-06-05', 1, 20000000),

-- Trans 4: Citra buys Samsung (1 unit)
(3, 2, '2023-06-10', 1, 15000000),

-- Trans 5: Eko buys Asus ROG (1 unit) -> REVENUE LEADER
(5, 4, '2023-06-12', 1, 25000000);

-- =============================================
-- SECTION 3: DATA ANALYSIS & BUSINESS INSIGHTS
-- =============================================

-- Case 1: Full Transaction Report
-- Objective: Retrieve detailed transaction history with customer and product names.
SELECT 
    t.transaction_id,
    t.transaction_date,
    c.full_name AS customer_name,
    p.product_name,
    p.category,
    t.quantity,
    t.total_amount
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id
JOIN products p ON t.product_id = p.product_id
ORDER BY t.transaction_date;

-- Case 2: Total Revenue
-- Objective: Calculate the total revenue generated by the store.
SELECT 
    SUM(total_amount) AS total_revenue
FROM transactions;

-- Case 3: Best Selling Product (By Volume)
-- Objective: Identify which product has the highest quantity sold.
-- Insight: AirPods Pro 2 is the volume leader (2 units sold).
SELECT 
    p.product_name,
    SUM(t.quantity) AS total_quantity_sold
FROM transactions t
JOIN products p ON t.product_id = p.product_id
GROUP BY p.product_name
ORDER BY total_quantity_sold DESC;

-- Case 4: Top Spender (Best Customer)
-- Objective: Identify the customer with the highest total spending.
SELECT 
    c.full_name,
    COUNT(t.transaction_id) AS transaction_frequency,
    SUM(t.total_amount) AS total_spending
FROM transactions t
JOIN customers c ON t.customer_id = c.customer_id
GROUP BY c.full_name
ORDER BY total_spending DESC
LIMIT 3;

-- Case 5: Revenue Leader (By Product Value)
-- Objective: Identify which product contributes the most to financial revenue.
-- Insight: Despite lower volume, Laptops (Asus & MacBook) generate the highest revenue.
SELECT 
    p.product_name,
    p.category,
    SUM(t.total_amount) AS total_revenue_contribution
FROM transactions t
JOIN products p ON t.product_id = p.product_id
GROUP BY p.product_name, p.category
ORDER BY total_revenue_contribution DESC;
